# vi: ft=tmux

#icons
arrow_right_filled="\uE0B0"
arrow_right_empty="\uE0B1"
arrow_left_filled="\uE0B2"
arrow_left_empty="\uE0B3"

# Set default terminal type
set -g default-terminal "xterm-256color"

# Set zsh as default shell
set-option -g default-shell $SHELL

# Automatically renumber tmux windows
set -g renumber-windows on

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Enable tmux mouse
set -g mouse on

# Powerline TMUX
set-option -g status on
set-option -g status-justify "centre"
set-option -g status-left-length 60
set-option -g status-right-length 90

set -g status-left "#[fg=black,bg=yellow] #{session_name} #[fg=yellow,bg=black]$arrow_right_filled"
set -g window-status-format "  #{window_index} #{window_name}  "
set-window-option -g window-status-current-format "#[fg=black,bg=brightred]$arrow_right_filled #{window_index} #{window_name} #[fg=brightred,bg=black]$arrow_right_filled"
set -g status-right "#[fg=brightgreen,bg=black]$arrow_left_filled#[fg=black,bg=brightgreen] %d %b %Y %H:%M:%S "

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'seebi/tmux-colors-solarized'
set -g @plugin 'tmux-plugins/tmux-sessionist'

set -g @colors-solarized 'dark'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
